# TF Syntax Basics

In [55]:
import tensorflow as tf

In [56]:
tf.compat.v1.disable_eager_execution() # important for version 1

print(tf.__version__)

2.9.1


## Building a Graph

In [57]:
hello = tf.constant("hello ")
world = tf.constant("world")

helloWorld = hello + world #Operation

type(helloWorld)

tensorflow.python.framework.ops.Tensor

In [58]:
with tf.compat.v1.Session() as sess:
    result = sess.run(helloWorld)

print(result)

b'hello world'


In [59]:
a = tf.constant(10)

b = tf.constant(20)

a + b # add_x:0 x = number of times run

<tf.Tensor 'add_5:0' shape=() dtype=int32>

In [60]:
c = a + b

with tf.compat.v1.Session() as sess:
    result = sess.run(c)

print(result)

30


In [62]:
const = tf.constant(10)

fill_mat = tf.fill([2,3],10)

my_zeros = tf.zeros((4,4))

my_ones = tf.ones((4,4))

myrandn = tf.compat.v1.random_normal((4,4),mean=0,stddev=1.0)

myrandu = tf.compat.v1.random_uniform((4,4),minval=0,maxval=1)


In [63]:
my_ops = [const, fill_mat, my_zeros, my_ones, myrandn, myrandu]

In [67]:
sess = tf.compat.v1.InteractiveSession()

for op in my_ops:
    result = sess.run(op)
    print("\n")
    print(result)



10


[[10 10 10]
 [10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.32160026 -0.0666789   0.2191344  -0.4476273 ]
 [-0.58521515  0.14821781  0.41573212  0.5105667 ]
 [ 0.83111125  0.39791614  1.2676114   0.85797083]
 [-1.2120475  -0.96325713 -0.5163599   1.7775667 ]]


[[0.30262566 0.74237657 0.46588874 0.27381468]
 [0.23411405 0.48216724 0.72223186 0.01397347]
 [0.40382767 0.37546945 0.632444   0.28950298]
 [0.6761224  0.6560956  0.8375248  0.10856378]]


C:\Users\flame\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py:1768: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [73]:
a = tf.constant([[1,2],
                 [3,4]])

b = tf.constant([[10],
                 [100]])

In [74]:
a.get_shape()

TensorShape([2, 2])

In [75]:
b.get_shape()

TensorShape([2, 1])

# Multiply of matrix

Remember the dot product this is last year highschool stuff

$$\begin{bmatrix} 1 & 2\\ 3 &  \end{bmatrix}$$ * $$\begin{bmatrix} 10 & \\ 3 &  \end{bmatrix}$$
[ 1  2 ] * [ 10 100 ] = 1 * 10 + 2 * 100 = 210
[ 3  4 ]              = 3 * 10 + 4 * 100 = 430

[ 1  2 ] * [ 10 100 ] = [ 210 ]
[ 3  4 ]                [ 430 ]



In [77]:
result = tf.matmul(a,b)

sess.run(result)

array([[210],
       [430]])