In [ ]:
# NumPy

import numpy as np

In [3]:
my_list = [1,2,3]

In [4]:
type(my_list)

list

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [9]:
np.arange(0,11,2) # from 0 to 10 step by 2

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(5) # digit

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,5)) # zero padding a tuple

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.linspace(2, 3, 5) #compared to arange this dose a evenly space between 2 and 3 of 5 spaces

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [24]:
np.random.randint(0, 10) # low number included High number is excluded

3

In [25]:
np.random.randint(0, 1000, (3,3)) # tuple "matric" filed with random numbers

array([[482,  95, 903],
       [948, 272,  34],
       [966, 240, 921]])

In [30]:
# to make sure we use the same random numbers we can use the seed function

np.random.seed(101) # OBS only in this cell !!!

np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [31]:
# Few usefull operations
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [32]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [33]:
arr.max()

95

In [34]:
arr.min()

9

In [35]:
arr.mean() # average

60.8

In [36]:
arr.argmax() # return the index position on the max

0

In [37]:
arr.reshape(2,5) " reshapes the array from 1 dimensional to 2 by 5"

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [39]:
mat = np.arange(0,100).reshape(10,10)

In [40]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [42]:
mat[0,1]

1

In [43]:
#get number 43

mat[4,3]

43

In [44]:
mat[:,0] # select all in the column

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
mat[0,:] # select all in the row

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
mat[0:3,0:3] # slice row and column mat[row,column]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [49]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [50]:
# return values higher than 50

my_filter = mat > 50 # boolean masking

In [51]:
mat[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])